spring:
    profiles:
        active: local
    application:
        name: ch15
---
spring:
    profiles: local
    datasource:
#        jdbc-url: jdbc:mysql://localhost:3306/order_system?serverTimezone=Asia/Seoul
        url: jdbc:mysql://localhost:3306/order_system?serverTimezone=Asia/Seoul
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            pool-name: hikari-cp
            maximum-pool-size: 5
            minimum-idle: 2
            connection-timeout: 1000
            idle-timeout: 20000
            max-lifetime: 180000
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true